### ISSUE TITLE
Feature Request: Merge all emails to one pdf

### ISSUE THREAD

**Issue by spongioblast** [nickrussler/eml-to-pdf-converter#4]
It would be great if there was an option to merge all converted emails to one PDF.

**Comment by nickrussler** [comment]
You can use the excellent [iText](http://itextpdf.com/) library to [concatenate](http://developers.itextpdf.com/examples/itext-action-second-edition/chapter-6#250-concatenate.java) PDF's. It is available under the AGPL license. Since i want to offer my code under a less restrictive license i can't use it. But you can write an AGPL licensed software that uses my tool and then iText.

**Comment by THausherr** [comment]
You could also use PDFMerger from PDFBox, which has an apache license.
